version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestLDSProject1234Project
  gitServerName: moaa
  gitUrl: https://github.com/Mohamed-Naufal-A-IBM
  gitUsername: Mohamed-Naufal-A-IBM
  gitBranch: main
